### ISSUE TITLE
Robot is driving a bit backward, if the target is exactly straight forward

### ISSUE THREAD

**Issue by AndyPermaRobotics** [zauberzeug/rosys#36]
Hi there!

I noticed an interesting behavior in my simulation environment. 
I thinks in reality it will happen rarely, but not never.

My szenario:
With a button click, I create a target pose that is exactly n meters in front (x-axis) of the current robots pose.
```python
new_point = current_pose.transform(Point(x=5, y=0))
goal_pose = Pose(x=new_point.x, y=new_point.y, yaw=current_pose.yaw)
```
afterwards I calculate a path with the path_planner:
```python
path = await path_planner.search(
    start=current_pose, goal=goal_pose, timeout=30
)
```

What happens is, that the robot is driving a bit backward, before it drives forward and after driving backward, the carrot is constantly behind the hook. This results in driving beyond the goal pose and afterwards driving backward again, to reach the goal_pose.

Some screenshots:
1. Start:
<img width="899" alt="image" src="https://github.com/zauberzeug/rosys/assets/129860214/2bbc2330-36ac-4277-a8b8-ff70e6a954c5">

2. Drive Backwards:
<img width="899" alt="image" src="https://github.com/zauberzeug/rosys/assets/129860214/98b48219-ad99-4123-bbc5-48cf7e656811">

3. Afterwards the carrot is behind the hook, while the robot is driving forward:
<img width="906" alt="image" src="https://github.com/zauberzeug/rosys/assets/129860214/3b62f771-98e5-40cb-ac61-784b06724525">

4. Drivings beyond the goal_pose:
<img width="903" alt="image" src="https://github.com/zauberzeug/rosys/assets/129860214/7ac231aa-195a-461c-a069-61480a04a414">

5. Drives backward, until the goal_pose is reached:
<img width="901" alt="image" src="https://github.com/zauberzeug/rosys/assets/129860214/4b3317bf-80a3-4e15-bb18-98f6f0473947">

The interesting part: If I shift the goal_pose just a little bit to the side (e.g. 1cm), everything works as expected and the bot drives forward only.

As far as I could debug the behavior, the Delaunay Path Planner says: 
`"INFO:rosys.delaunay_planner:found single spline to reach goal"`
I printed out the PathSegment that the path_planner returns:
`PathSegment(spline=Spline(0.000,0.000 ~ -2.500,0.000 ~ 7.500,0.000 ~ 5.000,0.000), backward=True)`

I looks like the forward PathSegment "is not healthy".
<img width="1019" alt="image" src="https://github.com/zauberzeug/rosys/assets/129860214/21a6f318-f52f-49f9-ab4f-f3dfd651a123">
but I don't know why.

Best regards
Andreas

**Comment by falkoschindler** [comment]
Hi Andreas,

That's an interesting bug! First I thought it's all about the internal workings of the path planner, which approximates the world with a triangular grid and searches a graph-based path from one node to another. Due to the grid resolution, the path might deviate from the theoretical optimum. But as the debug log says, a special case of a single spline from start to goal was found. So the problem might be caused by this single spline.

Here is a minimum reproduction to experiment with:
```py
import logging
import rosys
from nicegui import ui

logging.basicConfig(level=logging.DEBUG)

shape = rosys.geometry.Prism.default_robot_shape()
wheels = rosys.hardware.WheelsSimulation()
robot = rosys.hardware.RobotSimulation([wheels])
odometer = rosys.driving.Odometer(wheels)
driver = rosys.driving.Driver(wheels, odometer)
path_planner = rosys.pathplanning.PathPlanner(shape)

with ui.scene():
    rosys.driving.robot_object(shape, odometer, debug=True)

async def drive_straight():
    start_pose = odometer.prediction
    goal_pose = start_pose.transform_pose(rosys.geometry.Pose(x=1))
    path = await path_planner.search(start=start_pose, goal=goal_pose)
    logging.info(path)
    await driver.drive_path(path)

ui.button('Drive straight', on_click=drive_straight)

ui.run()
```

And there it is! The path segment is very unexpected:
```py
[PathSegment(spline=Spline(0.000,0.000 ~ -0.500,0.000 ~ 1.500,0.000 ~ 1.000,0.000), backward=True)]
```
The spline goes _backwards_ from (0,0) via control points (-0.5,0) and (1.5,0) to (1,0). We don't see the robot driving backwards, because the carrot is basically pushed perfectly straight, so the vehicle doesn't start to turn. But as we can see from the data, the path segment is actually supposed to be driven backwards.

So the question is why the single-spline solution is flipped. I'll look into it! 🙂
